CREATE TABLE IF NOT EXISTS `groups`(groupId INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT
, `group` ENUM('A','B','C','D','E','F','G','H') NOT NULL
, teamId INTEGER NOT NULL
, insertDate DATETIME DEFAULT NOW());