CREATE TABLE IF NOT EXISTS group_positions(group_pos_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT
, group_id INTEGER UNSIGNED NOT NULL
, team_id INTEGER UNSIGNED NOT NULL
, group_pos VARCHAR(2)
, date DATETIME );