CREATE TABLE IF NOT EXISTS teams_temp(id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT
, team_name VARCHAR(30) UNIQUE NOT NULL
, q_group ENUM('A','B','C','D','E','F','G','H') NOT NULL
, group_pos VARCHAR(2) NOT NULL );